# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
locale                   : "en-US"
title                    : "Huy H. Nguyen"
title_separator          : "-"
name                     : &name "Huy H. Nguyen"
description              : &description "Research in AI safety, security, privacy, and multimedia forensics."
url                      : https://honghuy127.github.io
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "honghuy127/honghuy127.github.io"
teaser                   :  # filename of teaser fallback teaser image placed in /images/, .e.g. "500x300.png"
breadcrumbs              : false # true, false (default)
words_per_minute         : 160
future                   : true
read_more                : "disabled" # if enabled, adds "Read more" links to excerpts
# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Social Sharing
twitter:
  username               : &honghuy127
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : "social-preview.png"
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : "Person"
  name                   : "Huy H. Nguyen"
  links:
    - "https://github.com/honghuy127"
    - "https://www.linkedin.com/in/nhhuy"
    - "https://scholar.google.com/citations?user=8q1km_cAAAAJ&hl=en"
    - "https://orcid.org/0000-0002-2000-7977"


# Site Author
author:
  name             : "Huy H. Nguyen"
  avatar           : "profile.jpg"
  bio              : "Researcher at SB Intuitions."
  location         : "Tokyo, Japan"
  employer         :
  pubmed           : 
  googlescholar    : "https://scholar.google.com/citations?user=8q1km_cAAAAJ&hl=en"
  email            :
  researchgate     : "https://www.researchgate.net/profile/Huy-Nguyen-187"
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : "honghuy127"
  google_plus      :
  keybase          :
  instagram        :
  impactstory      : #"https://profiles.impactstory.org/u/xxxx-xxxx-xxxx-xxxx"
  lastfm           :
  linkedin         : "nhhuy"
  orcid            : "https://orcid.org/0000-0002-2000-7977"
  pinterest        :
  soundcloud       :
  stackoverflow    : 
  steam            :
  tumblr           :
  twitter          : "honghuy127"
  vine             :
  weibo            :
  xing             :
  youtube          :
  wikipedia        :


# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
timezone: Asia/Tokyo # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
whitelist:
  - jekyll-sitemap
  - jemoji

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
